# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Temas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluguel',
            options={'verbose_name': 'aluguel', 'verbose_name_plural': 'Alugu\xe9is'},
        ),
    ]
