# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temas', '0002_auto_20190202_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=10, verbose_name='Telefone'),
        ),
    ]
