# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDeAmigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('nome_mae', models.CharField(max_length=20, verbose_name='Nome da M\xe3e')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('grupo_amigo', models.CharField(choices=[('', (('predio', 'Predio'), ('escola', 'Escola')))], default='', max_length=20, verbose_name='Grupo de Amigos')),
            ],
        ),
        migrations.CreateModel(
            name='CadastroDeRevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edicao', models.IntegerField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField()),
                ('etiqueta', models.CharField(max_length=20, verbose_name='Etiqueta')),
                ('cor', models.CharField(max_length=10, verbose_name='Cor')),
            ],
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome ')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(verbose_name='Data do Emprestimo')),
                ('data_devolucao', models.DateField(verbose_name='Data da Devolu\xe7ao')),
            ],
        ),
    ]
