# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.CharField(max_length=15, verbose_name='Data de Cria\xe7\xe3o')),
                ('tipo_despesa', models.CharField(choices=[('', (('remedio', 'Rem\xe9dio'), ('roupas', 'Roupas'), ('alimentos', 'Alimenta\xe7\xe3o'), ('educacao', 'Educa\xe7\xe3o'), ('transporte', 'Transporte'), ('outros', 'Outros')))], default='', max_length=150, verbose_name='Tipo de Despesa')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('forma_pagamento', models.CharField(choices=[('', (('dinheiro', 'Dinheiro'), ('cartao credito', 'Cart\xe3o de Cr\xe9dito'), ('cartao debito', 'Cart\xe3o de D\xe9bito'), ('cartao crediario', 'Cart\xe3o Credi\xe1rio'), ('cheque', 'Cheque')))], default='', max_length=40, verbose_name='Forma de Pagamento')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('quitado', models.BooleanField(verbose_name='Quitado')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
